name: ab-tag-provider #sdk-py-provider
version: 2.1.0
summary: Data Layer provider for Allen-Bradley Tags
title: ab-tag-provider #sdk-py-provider
description: |
  This app will find and add all data from Allen-Bradley Controllers on the local network to the data-layer 
base: core20
confinement: strict
grade: stable

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s

parts:
  provider:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer
    python-packages:  
      - ./whl/pylogix-0.8.13-py2.py3-none-any.whl
      - ./whl/pycomm3-1.2.11-py3-none-any.whl
            
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer